# preload = /home/Carlos/.dotfiles/imgs/Sith.jpg

# wallpaper = ,/home/Carlos/.dotfiles/imgs/Sith.jpg

# splash = false
# ipc = true

wallpaper {
    monitor = eDP-1
    path = ~/.dotfiles/imgs/Sith.jpg
    fit_mode = cover
}

splash = false
ipc = true