[font]
size = 22.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "MesloLGS NF"

[window]
opacity = 0.05

[colors.primary]
background = "#f20000"